### ISSUE TITLE
can't get this to run

### ISSUE THREAD

**Issue by evanrich** [rainforestautomation/Eagle-Http-API#7]
On a debian 8.3 box, I tried the following:

apt-get install python-pip

this installed python and pip, however your directions don't seem to work:

`

root@metrics:~# python
Python 2.7.9 (default, Mar  1 2015, 12:57:24)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from eagle_http import *
> > >  eagle = eagle_http('username', 'password', 'cloudid')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > NameError: name 'eagle_http' is not defined
> > > 
> > > `

and i can't get any further.  Any ideas?

Thanks!

**Comment by evanrich** [comment]
so I finally got it to work, but I don't know why.  

If I navigate to the path of the module and run python, it works:

![test](https://cloud.githubusercontent.com/assets/518320/15233171/7d413a88-185b-11e6-872f-a31c783badbb.PNG)

but if I run it from anywhere else in my path, or as a .py file, it fails with that message.
![testfail](https://cloud.githubusercontent.com/assets/518320/15233185/ab4cf5c0-185b-11e6-85d3-338468dd5484.PNG)

**Comment by evanrich** [comment]
I also have the following issues:

> > > eagle.InstantaneousDemand
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > AttributeError: eagle_http instance has no attribute 'InstantaneousDemand'
> > > eagle.InstantaneousDemand.Demand
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > AttributeError: eagle_http instance has no attribute 'InstantaneousDemand'

I've sort of got this working, by directly exporting the modules path to python:

export PYTHONPATH="${PYTHONPATH}:/usr/local/lib/python2.7/dist-packages/eagle_http"

but can't get individual stats, only the eagle.get_instantaneous_demand

**Comment by mattm401** [comment]
I am bumping into this issue myself, would love to hear if you're still working on this.

**Comment by Synetech** [comment]
I'm having the same "not defined" problem (in Windows), but if I try to run it from the module's directory (in site-packages), it gives this error when trying to import the module: `SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.final_url)?`
